### ISSUE TITLE
cl-bencode didn't decode `pieces` part

### ISSUE THREAD

**Issue by muyinliu** [nja/cl-bencode#2]
According [Torrent file - Wiki](https://en.wikipedia.org/wiki/Torrent_file), a `*.torrent` contains property `pieces`, the value of `pieces` is a string with length `(* (ceiling <length> <piece length>) 160)`(bit), each 160-bit as a binary SHA-1 hash of one piece.

Hope `cl-bencode` support decode property `pieces` soon.

**Comment by nja** [comment]
The full torrent file format is unfortunately beyond the scope of this little library.
