### ISSUE TITLE
It's not appropriate to decode torrent files by `read-char`

### ISSUE THREAD

**Issue by muyinliu** [nja/cl-bencode#3]
Because some `*.torrent` files support property `encoding`(for example GBK), `path.utf-8` or `name.utf-8`, `read-char` might cause exceptions or generate wrong result. It's better to use `read-byte`.

**Comment by nja** [comment]
If you take a look at the code, you can see that the bytes are actually being read with `read-byte`.

The decoding of strings from binary to characters can be controlled with the `:external-format` parameter.

`BENCODE> (decode (encode "räksmörgås" nil :external-format :utf-8) :external-format :utf-8)
"räksmörgås"`
`BENCODE> (decode (encode "räksmörgås" nil :external-format :utf-8) :external-format :latin1)
"rÃ¤ksmÃ¶rgÃ¥s"`
`BENCODE>`

It relies on flexi-streams for decoding. If there is no flexi-stream support for the encoding you need, perhaps you could suppress decoding with `*binary-key-p*` and decode the bytes by some other means.

**Comment by muyinliu** [comment]
Some torrent files contain multiple charsets in single file...
